language: node_js
node_js:
  - 10
  - 12
  - 14

script:
  - npm run build
  - npm run test
  - npm run lint
  - npm run format -- --check --write false

deploy:
  - provider: npm
    edge: true
    on:
      tags: true
      node_js: 12
